### ISSUE TITLE
docker-compose.yml file missing from repo

### ISSUE THREAD

**Issue by mcred** [RestComm/netflix-oss-tracker-infra#2]
The following section of the `osstracker.yml` role has the following section:
```
- name: Deploy OSSTracker
  hosts: osstracker
  become: true
  tasks:
    - copy:
        src: ../../docker-compose.yml
        dest: /opt/osstracker/
        mode: 0644
    - copy:
        src: ../../osstracker-ddl
        dest: /opt/osstracker/
        mode: 0644
```

`../../docker-compose.yml` is missing from the repository. Could someone add this file?

**Comment by mcred** [comment]
I was able to resolve this issue. The docker-compose file from the netflix/osstracker repo is what was missing. This was not clear in the documentation for this repo.

**Comment by gsaslis** [comment]
@mcred care to make another PR that adds this info in the README ?

**Comment by mcred** [comment]
The solution ended up being a little more involved that just documentation. The issues comes from `./ansible/plays/osstracker.yml`. 

```yml
- name: Deploy OSSTracker
  hosts: osstracker
  become: true
  tasks:
    - copy:
        src: ../../docker-compose.yml
        dest: /opt/osstracker/
        mode: 0644
    - copy:
        src: ../../osstracker-ddl
        dest: /opt/osstracker/
        mode: 0644
```

The `src` for the copy tasks refer to the root directory which is the root for `netflix-oss-tracker-infra` and not `netflix/osstracker` where the files are located. Both of these repos are tracked by git and can't share the same root space. I solved this problem by adding `netflix/osstracker` as a submodule in directory `./netflix-osstracker` and updated the copy tasks to look like:

```yml
- name: Deploy OSSTracker
  hosts: osstracker
  become: true
  tasks:
    - copy:
        src: ../../netflix-osstracker/docker-compose.yml
        dest: /opt/osstracker/
        mode: 0644
    - copy:
        src: ../../netflix-osstracker/osstracker-ddl
        dest: /opt/osstracker/
        mode: 0644
```

I know a lot of people don't like submodules, so there are a few ways to solve this. What do you think about adding a parameter for `netflix/osstracker` directory and pass it to the osstracker play?
